Repository WordPress/secure-custom-fields, pull requests merged in 2025-04, with the labels that each got.

#101 Revert text domain change
  includes/api/api-template.php
Labels: [Type] Bug

#104 Refactor: Prevent some `undefined` array key warnings.
  includes/compatibility.php
  includes/fields/class-acf-field-button-group.php
  includes/fields/class-acf-field-checkbox.php
  includes/fields/class-acf-field-file.php
  includes/fields/class-acf-field-number.php
  includes/fields/class-acf-field-select.php
  includes/fields/class-acf-field-text.php
  includes/fields/class-acf-field-true_false.php
Labels: [Type] Code Quality

#106 Fix: Small fix on field link.
  assets/src/js/_acf-field-link.js
Labels: [Type] Bug

#107 Backport 6.4.2 readme changes
  readme.txt
  secure-custom-fields.php
Labels: documentation, [Status] Needs Review

#109 Languages: es_EC is now served via w.org packs
  lang/secure-custom-fields-es_EC.l10n.php
  lang/secure-custom-fields-es_EC.mo
  lang/secure-custom-fields-es_EC.po
Labels: [Type] Enhancement, [Status] Needs Review

#110 Translations: add script to remove 90% translations
  bin/prepare-release.php
  bin/update-translations.php
  composer.json
Labels: [Type] Enhancement, [Status] Needs Review

#117 Fixes phpstan issues
  bin/baseline.neon
  includes/acf-input-functions.php
Labels: [Type] Code Quality

#116 Fix up code against phpstan
  bin/baseline.neon
  includes/acf-field-functions.php
Labels: [Type] Code Quality

#118 Update initialization of the `acfL10n` object to ensure it's available globally
  assets/src/js/_acf.js
Labels: [Type] Code Quality

#119 phpstan fixes (includes/admin/*)
  bin/baseline.neon
  includes/admin/admin-internal-post-type-list.php
  includes/admin/post-types/admin-field-groups.php
  includes/admin/post-types/admin-post-type.php
Labels: [Type] Code Quality

#113 Framework and admin screen to add new features as opt-in
  .gitignore
  includes/admin/beta-features.php
  includes/admin/beta-features/class-scf-beta-feature-editor-sidebar.php
  includes/admin/beta-features/class-scf-beta-feature.php
  includes/admin/beta-features/index.php
  includes/admin/views/beta-features/beta-features.php
  includes/admin/views/global/navigation.php
  secure-custom-fields.php
  tests/php/test-admin-beta-features.php
Labels: [Type] Enhancement, [Status] Needs Review
