Repository WordPress/secure-custom-fields, pull requests merged in 2025-03, with the labels that each got.

#72 Correct typo on image alt tag
  includes/admin/views/global/navigation.php
  lang/secure-custom-fields-ar.po
  lang/secure-custom-fields-bg_BG.po
  lang/secure-custom-fields-ca.po
  lang/secure-custom-fields-cs_CZ.po
  lang/secure-custom-fields-da_DK.po
  lang/secure-custom-fields-de_CH.po
  lang/secure-custom-fields-de_DE.po
  lang/secure-custom-fields-de_DE_formal.po
  lang/secure-custom-fields-el.po
  lang/secure-custom-fields-en_CA.po
  lang/secure-custom-fields-en_GB.po
  lang/secure-custom-fields-en_ZA.po
  lang/secure-custom-fields-es_CO.po
  lang/secure-custom-fields-es_CR.po
  lang/secure-custom-fields-es_EC.po
  lang/secure-custom-fields-es_MX.po
  lang/secure-custom-fields-es_VE.po
  lang/secure-custom-fields-fa_AF.po
  lang/secure-custom-fields-fa_IR.po
  lang/secure-custom-fields-fi.po
  lang/secure-custom-fields-fr_CA.po
  lang/secure-custom-fields-fr_FR.po
  lang/secure-custom-fields-gl_ES.po
  lang/secure-custom-fields-gu.po
  lang/secure-custom-fields-he_IL.po
  lang/secure-custom-fields-hr.po
  lang/secure-custom-fields-hu_HU.po
  lang/secure-custom-fields-id_ID.po
  lang/secure-custom-fields-it_IT.po
  lang/secure-custom-fields-ja.po
  lang/secure-custom-fields-ko_KR.po
  lang/secure-custom-fields-nb_NO.po
  lang/secure-custom-fields-nl_NL_formal.po
  lang/secure-custom-fields-pl_PL.po
  lang/secure-custom-fields-pt_AO.po
  lang/secure-custom-fields-pt_BR.po
  lang/secure-custom-fields-pt_PT.po
  lang/secure-custom-fields-ro_RO.po
  lang/secure-custom-fields-sk_SK.po
  lang/secure-custom-fields-tr_TR.po
  lang/secure-custom-fields-uk.po
  lang/secure-custom-fields-zh_TW.po
  lang/secure-custom-fields.pot
Labels: [Type] Bug

#76 Fix typos in JS files
  assets/inc/color-picker-alpha/wp-color-picker-alpha.js
  assets/inc/select2/3/select2.js
  assets/inc/select2/4/select2.full.js
  assets/inc/select2/4/select2.js
  assets/inc/timepicker/jquery-ui-timepicker-addon.js
  assets/src/js/_acf-compatibility.js
  assets/src/js/_acf-condition.js
  assets/src/js/_acf-field-accordion.js
  assets/src/js/_acf-field-google-map.js
  assets/src/js/_acf-field.js
  assets/src/js/_acf-helpers.js
  assets/src/js/_acf-media.js
  assets/src/js/_acf-model.js
  assets/src/js/_acf-postbox.js
  assets/src/js/_acf-select2.js
  assets/src/js/_acf-tooltip.js
  assets/src/js/_acf-validation.js
  assets/src/js/_acf.js
  assets/src/js/_browse-fields-modal.js
  assets/src/js/_field-group-conditions.js
  assets/src/js/_field-group-field.js
  assets/src/js/pro/_acf-setting-clone.js
Labels: [Type] Bug

#77 Fix typos in misc files
  docs/bin/generate-parsed-md.php
  docs/code-reference/META.md
Labels: [Type] Bug

#81 Form Post: Fix PHPStan and PHPCS issues.
  includes/forms/form-post.php
  tests/php/includes/forms/test-form-post.php
Labels: [Type] Bug, [Status] Awaiting Author Response

#44 Add nav menu field to scf
  docs/features/field/nav_menu/index.md
  docs/features/field/nav_menu/tutorial.md
  includes/fields/class-acf-field-nav-menu.php
  secure-custom-fields.php
Labels: [Type] Enhancement

#91 E2E Testing: Setting up the environment.
  .github/workflows/e2e.yml
  .gitignore
  package-lock.json
  package.json
  playwright.config.ts
  tests/e2e/plugin-activation.spec.ts
Labels: [Type] Enhancement
