Repository WordPress/secure-custom-fields, pull requests merged in 2025-06, with the labels that each got.

#170 Command Palette: Add command to edit CPT definitions
  assets/src/js/commands/custom-post-type-commands.js
  includes/admin/admin-commands.php
Labels: [Type] Enhancement

#175 Block Bindings: Add editor preview to acf-field source.
  assets/src/js/bindings/index.js
  assets/src/js/bindings/sources.js
  includes/Blocks/Bindings.php
  includes/assets.php
  webpack.config.js
Labels: [Type] Enhancement

#182 Bug: Changing a field type enables the “Allow Access to Value in Editor UI” setting.
  includes/fields/class-acf-field.php
Labels: [Type] Bug, Backport from upstream

#186 Bug: Fix AJAX repeater pagination.
  includes/api/api-helpers.php
  includes/fields/class-acf-field-repeater.php
Labels: [Type] Bug, Backport from upstream

#177 Enhancement: Add new `acf/fields/icon_picker/{tab_name}/icons` filter
  assets/src/js/_acf-field-icon-picker.js
  assets/src/sass/_acf-icon-picker.scss
  assets/src/sass/acf-global.scss
  includes/fields/class-acf-field-icon_picker.php
Labels: [Type] Enhancement, Backport from upstream
