Repository WordPress/secure-custom-fields, pull requests merged in 2025-05, with the labels that each got.

#124 Beta feature: Add endpoint to retrieve custom fields of a post type.
  includes/admin/beta-features/class-scf-beta-feature-editor-sidebar.php
  includes/rest-api.php
  includes/rest-api/class-acf-rest-types-endpoint.php
  secure-custom-fields.php
  tests/php/test-admin-beta-features.php
Labels: [Type] Enhancement

#114 Allow config errors to be display to users
  includes/api/api-template.php
Labels: [Type] Enhancement

#108 Correct stable release generation
  bin/prepare-release.php
Labels: [Type] Bug, [Status] Needs Review

#122 Remaining phpstan issues
  bin/baseline.neon
  includes/class-acf-internal-post-type.php
  includes/class-acf-site-health.php
  includes/fields/class-acf-field-checkbox.php
  includes/fields/class-acf-field-clone.php
  includes/fields/class-acf-field-google-map.php
  includes/fields/class-acf-field-group.php
  includes/fields/class-acf-field-oembed.php
  includes/fields/class-acf-field-repeater.php
  includes/fields/class-acf-field-user.php
  includes/forms/form-nav-menu.php
  includes/forms/form-post.php
  includes/forms/form-widget.php
  includes/l10n.php
  includes/local-fields.php
  includes/local-json.php
  includes/local-meta.php
  includes/locations/abstract-acf-legacy-location.php
  includes/loop.php
  includes/revisions.php
  includes/validation.php
Labels: [Type] Code Quality

#129 Specify the version refers to `SCF` in `@since` annotations
  assets/src/js/_acf-validation.js
  docs/code-reference/admin/admin-notices-file.md
  docs/code-reference/api/api-template-file.md
  docs/code-reference/validation-file.md
  includes/admin/admin-notices.php
  includes/admin/beta-features.php
  includes/admin/beta-features/class-scf-beta-feature-editor-sidebar.php
  includes/admin/beta-features/class-scf-beta-feature.php
  includes/admin/views/beta-features/beta-features.php
  includes/api/api-template.php
  includes/fields/class-acf-field-clone.php
  includes/fields/class-acf-field-nav-menu.php
  includes/fields/class-acf-field-output.php
  includes/locations.php
  includes/rest-api.php
  includes/rest-api/class-acf-rest-types-endpoint.php
  includes/validation.php
  secure-custom-fields.php
Labels: [Type] Code Quality

#130 Code Quality: Remove filename WPCS rule to be able to use PSR-4 autoload.
  .phpcs.xml.dist
Labels: [Type] Code Quality

#132 Bug: Fix repeater fields not showing in admin.
  includes/acf-hook-functions.php
Labels: [Type] Bug

#121 Add Command Palette support
  assets/src/js/commands/admin-commands.js
  assets/src/js/commands/custom-post-type-commands.js
  includes/admin/admin-commands.php
  includes/assets.php
  package-lock.json
  package.json
  secure-custom-fields.php
  webpack.config.js
Labels: [Type] Enhancement

#133 Tests: Add block e2e experiment.
  tests/e2e/field-type-text-with-scf-block.spec.ts
  tests/e2e/plugins/blocks/scf-movie-title-block/block.json
  tests/e2e/plugins/blocks/scf-movie-title-block/template.php
  tests/e2e/plugins/scf-test-get-field-scf-block.php
Labels: [Type] Code Quality

#134 Testing: Add repeater e2e test
  tests/e2e/field-type-repeater.spec.ts
  tests/e2e/field-type-text-with-scf-block.spec.ts
  tests/e2e/plugins/scf-test-get-repeater-field.php
Labels: [Type] Code Quality

#99 Add composer installation to docs/welcome
  docs/welcome/installation.md
Labels: documentation

#135 Fix: SCF Blocks are now forced into preview mode when editing a synced pattern.
  assets/src/js/pro/_acf-blocks.js
Labels: [Type] Bug
